your mom sucks more than a russian conscript

diff --git a/client b/client
--- a/client
+++ b/client
@@ -18,7 +18,8 @@ while true; do
 done
 
 if [ -z "$bin" ]; then
-    echo "I can't find $0 lol rawr"
+    echo "🥴 I can't find $0 lol rawr OwO"
+    exit 1
 fi
 
 $bin $@
